### ISSUE TITLE
Several Problems.

### ISSUE THREAD

**Issue by 100Max** [IsVipiOfficial/IsVipi-OSSN#16]
#1: Can't join your forum at your site. probably why not many people are man. :-/
- I fill out everything in the forum reg.. all checked. all good.
Then you get: An Error Has Occurred! Sorry Guest, you are banned from using this forum!
lol really? I never even used the forum.. cause you can not even join it.
So please fix that. and you would have more people on your forum. thanks.  
I'd rather use your forum instead of here.

#2: Seems to be a problem with mysql 5.7.... or maybe something else?
* Everything installs great.. no errors.. but it does not write the admin name to the database. O_O
.. nor sign ups work.. nor the logo loads.. It does create the database.. tables and all.
windows: Apache 2.4+  ..mod rewrite on.. php 5.6+.. sql 5.7.23

* This all works great on my Android Test web server setup. And looks very nice. and was fast.
... but not working on me main live setup. yet.

* Also.. you should do away with remote files: 
   CSS: maxcdn.bootstrapcdn (just add the css file.. and not connect remotely.)
   AND remote google fonts. (remove or download the font and add it.)

* But anyway.. please fix the forum signups... add: 100Max please. thanks.
I'm sure a lot of people have been trying to join your forum as well.

  happy new year man!

* EDIT: 1-2-19
* Fixed logo.. and mcrypt error upon looking at page source. 
 + s_Settings did not write the values. It did this time. 
 + Still will Not add a username upon install or signup.) huhhh.....
 ...guess I'll just find another script..

**Comment by IsVipiOfficial** [comment]
I am sorry for the troubles you have faced with our forum and the script so far. We recently received quite a number of spam accounts on our forum and had to blacklist certain domains and IPs. We have since cleared the log and ban triggers so you should be able to create an account. Once again, sorry about that.

As for the points you have raised above concerning the script, they are valid and we are looking into it. If you happen to create an account on our forum, please list all the issues you encounter. We check our forum more often than we do here. Also, if you are interested in contributing your enhancements of the script, or bug fixes, please let us know. We are a little short-handed right now and we can only spare a few hours a week to fix bugs and add new features.

I also hope that this response is not too late.
